apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-primos
  namespace: primos
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: api-primos              # procura Services com este label
  namespaceSelector:
    matchNames:
      - primos
  endpoints:
    - port: http                   # nome da porta no Service
      path: /metrics
      interval: 15s